---
- name: "install package key"
  apt_key:
    url: http://packages.fluentbit.io/fluentbit.key
    state: present
  register: result

- name: "Check HTTPS transport is available to APT"
  apt:
    name: "apt-transport-https"
    state: "present"
    update_cache: "yes"

- name: "install repo"
  apt_repository:
    repo: 'deb https://packages.fluentbit.io/ubuntu/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main'
    state: present
  register: result
  when: result is changed

- name: "update repo cache"
  apt:
    update_cache: yes
  when: result is changed
