---
- include_tasks: yum.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: apt.yml
  when: ansible_os_family == 'Debian'

- name: "install"
  package:
    name: td-agent-bit
    state: latest

- name: "create config rsyslog - Unix socket mode over UDP"
  template:
    src: 60-fluent-bit.conf.j2
    dest: /etc/rsyslog.d/60-fluent-bit.conf

- name: "restart rsyslog"
  service:
    name: rsyslog
    state: restarted


- name: "journald to forward logs to rsyslog"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^.ForwardToSyslog=[yes|no]"
    line: "ForwardToSyslog=yes"
    state: present
  notify: restart-journald-fluent-bit

- name: "place parsers file"
  template:
    src: "parsers.conf.j2"
    dest: "/etc/td-agent-bit/parsers.conf"

- name: "place FluentBit configuration file"
  template:
    src: "td-agent-bit.conf.j2"
    dest: "{{ fluentbit_main_configuration }}"

- name: "enable service td-agent-bit"
  service:
    name: "td-agent-bit"
    state: "restarted"
    enabled: "yes"

- name: "set permissions for Syslog Unix socket"
  file:
    path: /tmp/fluent-bit.sock
    mode: 0666
